import { NativeModules } from 'react-native';

const {
  REVENUE_PRECISION_ESTIMATED,
  REVENUE_PRECISION_PRECISE,
  REVENUE_PRECISION_PUBLISHER_PROVIDED,
  REVENUE_PRECISION_UNKNOWN,
} = NativeModules.RNAppModule.getConstants?.() ?? {};

export enum RevenuePrecisions {
  ESTIMATED = REVENUE_PRECISION_ESTIMATED,
  PRECISE = REVENUE_PRECISION_PRECISE,
  PUBLISHER_PROVIDED = REVENUE_PRECISION_PUBLISHER_PROVIDED,
  UNKNOWN = REVENUE_PRECISION_UNKNOWN,
}
