name: Code Quality Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Lint code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json', 'RNGoogleMobileAdsExample/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Lint
        run: yarn lint:code
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'eslint-report.json'
      - name: Upload ESLint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report.json
          path: eslint-report.json

  typescript:
    name: TypeScript Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json', 'RNGoogleMobileAdsExample/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
      - name: Lint
        run: yarn tsc:compile

  # typedoc:
  #   name: TypeDoc Generation
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
  #     - uses: actions/cache@v4
  #       name: Yarn Cache
  #       id: yarn-cache
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}-with-website
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Yarn Install
  #       uses: nick-fields/retry@v3
  #       with:
  #         timeout_minutes: 3
  #         retry_wait_seconds: 30
  #         max_attempts: 3
  #         command: yarn --no-audit --prefer-offline
  #     - name: Yarn Install (Website)
  #       uses: nick-fields/retry@v3
  #       with:
  #         timeout_minutes: 3
  #         retry_wait_seconds: 30
  #         max_attempts: 3
  #         command: cd website && yarn --no-audit --prefer-offline
  #     - name: Generate TypeDoc
  #       run: node -e "require('./website/scripts/generate-typedoc').generateTypedoc()"
